export const selectorsConfig = {
  mapContainer: "#mapbox-map",
  sidebarWrapper: ".sidebar",
  sidebarMap: ".sidebar-map",
  sidebarBeach: ".sidebar-beach",
  beachListContainer: "#beach-list-container",
  toggleButton: "#toggle-button",
  closeButton: ".close-button",
  resetButton: "#reset-button",
  backButton: ".back-button",
  fullscreenToggle: "#fullscreen-toggle",
  errorContainer: ".error-container",
  searchInput: "#search-input",
  searchContainer: ".search-container",
  searchResults: ".search-results",
  navigationButtons: ".navigation-buttons",
  aboutButton: "#about-button",
  homeButton: "#home-button",
  citiesButton: "#cities-button",
  beachButton: "#beach-button",
  poisButton: "#pois-button",
  featuresButton: "#features-button",
};

export const uiConfig = {
  mapFlySpeedMultiplier: 1.5,
  renderDelayInMs: 150,
  popupOffsetInPixels: 32,
  listItemHeightInPixels: 80,
};

export const featureConfig = {
  state: {
    displayTemplate: "State: {Name}",
    dataMapping: {
      Name: "Name",
      Description: "Description",
      Region: "Region",
      "State Code": "State Code",
      "Country Code": "Country Code",
      "Total Beaches": "Total Beaches",
      Type: "Type",
    },
  },
  region: {
    displayTemplate: "Region: {Name}",
    dataMapping: {
      Name: "Name",
      Description: "Description",
      "State Code": "State Code",
      "Country Code": "Country Code",
      "Total Beaches": "Total Beaches",
      Type: "Type",
    },
  },
  beach: {
    displayTemplate: "Beach: {Name}",
    dataMapping: {
      Name: "Name",
      Description: "Description",
      Address: "Address",
      City: "City",
      County: "County",
      "State Code": "State Code",
      "Country Code": "Country Code",
      "Zip Code": "Zip Code",
      Latitude: "Latitude",
      Longitude: "Longitude",
      Type: "Type",
      "Item ID": "Item ID",
      Hours: "Hours",
      Phone: "Phone",
      Website: "Website",
      Restrooms: "Restrooms",
      Showers: "Showers",
      "Pets Allowed": "Pets Allowed",
      style: { display: "inline" },
    },
  },
  poi: {
    displayTemplate: "POI: {Name}",
    dataMapping: {
      Name: "Name",
      Description: "Description",
      Address: "Address",
      City: "City",
      County: "County",
      "State Code": "State Code",
      "Country Code": "Country Code",
      "Zip Code": "Zip Code",
      Latitude: "Latitude",
      Longitude: "Longitude",
      Type: "Type",
      "Item ID": "Item ID",
      Hours: "Hours",
      Phone: "Phone",
      Website: "Website",
      style: { display: "inline" },
    },
  },
}; 